### ISSUE TITLE
Miner Duplication Glitch

### ISSUE THREAD

**Issue by n0807701j2d2** [GingerWalnut/SQ5.0Public#197] opened 2018-02-23 22:22 UTC
I was attempting to set up an auto-cobble machine using a miner and an auto-cobble generator, but while testing by placing blocks in front of the miner, I found that the chest would fill up with the cobble without breaking the block. The miner would not move forwards and was collecting a lot of blocks. When I tried this with another block (cyan clay), I found the same thing happened. The configuration of blocks I found that triggered this was a 3x3 cobble wall with 4 cobble on the front at the corners.

My IGN is Jurgmania, and I found this glitch today.

**Comment by n0807701j2d2** [comment] 2018-02-25 21:37
This is kinda important. Please look at this?

**Comment by GingerWalnut** [comment] 2018-03-03 00:57
Should be fixed

**Closed by GingerWalnut** 2018-03-03 00:57 UTC

**Comment by n0807701j2d2** [comment] 2018-03-17 20:40
Not fixed, trying to start an auto-cobble machine again, the blocks weren't breaking and the chest was filling up. Tried it again with a random block (Stone Brick) and it wouldn't break the block, just put it in the chest.

**Comment by n0807701j2d2** [comment] 2018-03-17 20:45
@GingerWalnut

**Comment by Laserlance141** [comment] 2018-03-18 02:20
Yes, this i think might be caused by an interaction with block 36, which sometimes appear from pistons
