### ISSUE TITLE
Dissapearing items from droppers

### ISSUE THREAD

**Issue by Sofetios** [GingerWalnut/SQ5.0Public#88] opened 2018-01-08 17:12 UTC
this has happened twice now where i load my 12 droppers full of carrots and potatoes and then fly them directly to spawn. upon arrival and opening the droppers, around half the items are gone. I dont know if it is something to do with leaving the planet or what but i cant reliably use droppers. There was not time window where someone could have taken any, even invisibly.

**Comment by martinjonsson01** [comment] 2018-01-08 17:55
Similar to #83 but not caused by a server crash. Won't mark as duplicate.

**Comment by GingerWalnut** [comment] 2018-01-09 00:01
Duplicate of #77

**Closed by GingerWalnut** 2018-01-09 00:01 UTC
Labels: Priority High, Ships Bug
