### ISSUE TITLE
Magma cubes on Ifizo turn invisible

### ISSUE THREAD

**Issue by daredevil28** [GingerWalnut/SQ5.0Public#31] opened 2017-12-28 18:10 UTC
Magma cubes turn invisible on Ifizo. They stay at that exact same spot and do not move. They can constantly hurt you.

**Comment by martinjonsson01** [comment] 2017-12-29 22:00
Looks like duplicate of #9

**Closed by martinjonsson01** 2017-12-29 22:00 UTC
Labels: Duplicate

**Comment by daredevil28** [comment] 2018-01-01 01:41
Doesn't seem like a duplicate, as you can not see the magma cubes (getting hit does make the magma cubes sound)

**Comment by martinjonsson01** [comment] 2018-01-01 01:56
The other issue describes invisible entities, this issue describes invisible entities, do you not think they are caused by the same bug?

**Comment by daredevil28** [comment] 2018-01-01 01:58
As I see it bug #9 describes an I skeleton, and this one an invisible magma cubes. It could be related but I am not sure about that.

**Comment by daredevil28** [comment] 2018-01-01 01:58
Invincible skeleton*

**Comment by martinjonsson01** [comment] 2018-01-01 02:01
No, #9 describes invincible and invisible mobs (look at the title). In a comment they provide an example of a mob who is only invincible, but the issue itself describes invisible entities.
