### ISSUE TITLE
Thrusters give xp orbs when broken, but not the item

### ISSUE THREAD

**Issue by soronthar** [GingerWalnut/SQ5.0Public#32] opened 2017-12-28 19:25 UTC
I broke two thrusters and they gave me xp orbs but not the item. I though it was something related to the ship, so I gave myself another one, placed it and broke it, same result.

I used a stone pickaxe, but that worked 2 min before.

**Comment by martinjonsson01** [comment] 2017-12-29 22:01
Duplicate of #16

**Closed by martinjonsson01** 2017-12-29 22:01 UTC
Labels: Duplicate
