### ISSUE TITLE
Auto Farms placing Dirt

### ISSUE THREAD

**Issue by n0807701j2d2** [GingerWalnut/SQ5.0Public#140] opened 2018-01-16 16:10 UTC
When I wired my autofarm, it started to place tilled dirt on the layer of dirt I'd intended to have as the farmed area.

-NeedToCut_it

**Comment by martinjonsson01** [comment] 2018-01-16 17:19
Duplicate of #134

**Closed by martinjonsson01** 2018-01-16 17:19 UTC
