### ISSUE TITLE
Permissions on spawn station

### ISSUE THREAD

**Issue by n0807701j2d2** [GingerWalnut/SQ5.0Public#22] opened 2017-12-26 18:47 UTC
I tried to retract/extend my docking tube, but it wouldn't, telling me I needed an admin's permissions to build. Also, I could not open the doors at spawn with the pressure plates, so I had to ask Java for help getting in.

-NeedToCut_it

**Comment by martinjonsson01** [comment] 2017-12-29 21:56
Duplicate of #12

**Closed by martinjonsson01** 2017-12-29 21:56 UTC
Labels: Duplicate
