### ISSUE TITLE
Drills randomly not working.

### ISSUE THREAD

**Issue by Psych0bob** [GingerWalnut/SQ5.0Public#220] opened 2018-04-06 21:01 UTC
Occasionally when building and powering drills they randomly don't work. Activating them just has them sit there. Breaking then re powering the block seems to fix it, though at the cost of whatever energy was in the block.

**Comment by martinjonsson01** [comment] 2018-04-10 16:39
Bugs almost never randomly occur, they're most likely caused by a set of very specific circumstances, so if you happen to have any more information regarding the situation in which this bug occurs then include that in the issue if possible.

**Comment by ironjim92** [comment] 2018-06-29 11:49
drills arent working again, they just dupe blocks but dont actually take any away and just sit there

**Comment by GingerWalnut** [comment] 2018-07-15 20:30
This should be fixed

**Closed as completed by GingerWalnut** 2018-07-15 20:30 UTC
Labels: SQTech Bug, Priority Med
