### ISSUE TITLE
Unholy Colony Permission's Error Spam Bug from Oblivion

### ISSUE THREAD

**Issue by SomethingSomethingAllison** [GingerWalnut/SQ5.0Public#98] opened 2018-01-10 07:21 UTC
I placed down a radar block in my ship, and piloted it within the colony Covenant (My Colony on Arenstad) and then it started spamming me with the classical 'you do not have permissions to interact with blocks in this colony' rendering me completely incapable of reading chat. I have re logged 3 times and completely shutdown 3 times as well, with no differences. Old and Zoreck came to my rescue and tried to fix it. we tried removing the radar, moving the ship out of the claim, and still no results. Old said the only way for this to be fixed at that time was a restart, Old suggested I report this to find a solution to this truly unholy bug.
![2018-01-10_00 48 54](https://user-images.githubusercontent.com/35288651/34760235-83480222-f5a4-11e7-87f3-a65a91627c26.png)

**Comment by martinjonsson01** [comment] 2018-01-10 12:57
Duplicate of #97

**Closed by martinjonsson01** 2018-01-10 12:57 UTC
Labels: Duplicate
