### ISSUE TITLE
Droppers losing  content

### ISSUE THREAD

**Issue by soronthar** [GingerWalnut/SQ5.0Public#77] opened 2018-01-05 01:01 UTC
Sometimes droppers are losing part or all of its content. It seems to happen when traveling to/from space, and happened on different planets.

**Comment by rocky0121** [comment] 2018-01-05 01:09
i can confirm this happened to me as well on arenstad, but the contents reappeared after a repilot

**Comment by Jarkyc** [comment] 2018-01-05 02:33
can confirm this happened to me 2 times, during the leaving and entering of planets. Mods helped me though.

**Comment by GingerWalnut** [comment] 2018-01-17 02:39
Possible fix for this at the next restart

**Comment by GingerWalnut** [comment] 2018-04-17 16:54
Going to close this since I havn't heard a report of this recently, open a new issue if it is still happening

**Closed by GingerWalnut** 2018-04-17 16:54 UTC
Labels: Priority High, Ships Bug
