### ISSUE TITLE
I cant make a ship bigger than 500 blocks

### ISSUE THREAD

**Issue by MemeMaster77** [GingerWalnut/SQ5.0Public#46] opened 2017-12-30 03:27 UTC
I made big boy ship and I cant pilot it and it gives me a message saying it has to be 500 blocks or less even though i have ranked up twice so i should be able to make a larger ship.

**Comment by martinjonsson01** [comment] 2017-12-30 21:31
Duplicate of #14

**Closed by martinjonsson01** 2017-12-30 21:31 UTC
Labels: Duplicate
