### ISSUE TITLE
Blocks not regening in claims at Alexandria

### ISSUE THREAD

**Issue by flaammeer** [GingerWalnut/SQ5.0Public#237] opened 2018-05-14 02:48 UTC
Ive noticed a lot of glass panes missing and some random blocks of stone granite and andesite after we experienced an attack using ship cannons. The players who attacked were staff and they repaired what we immediately noticed but as i inspected more and looked around i noticed a lot of random blocks missing.

**Comment by GingerWalnut** [comment] 2018-06-03 05:20
Duplicate of #233

**Closed as completed by GingerWalnut** 2018-06-03 05:20 UTC
