### ISSUE TITLE
Pistons glitch

### ISSUE THREAD

**Issue by GroxTerror** [GingerWalnut/SQ5.0Public#185] opened 2018-02-07 22:38 UTC
Had this occur several weeks ago and never bothered to report it. I have a piston door in my base that operates off of a T-flip-flop switch hooked to a button. I noticed it stopped working one day and found that the pistons created some glitched blocks. These are where the door's pistons are supposed to extend, and where the output block is supposed to move in the T-flip-flop. I can't place blocks in these spaces, pistons cannot extend into them, liquids cannot flow, etc. but they can be walked through.

Coordinates for these: (Sabaka)
1113, 53, 1626
1113, 54, 1626
1112, 54, 1626
1117, 57, 1628

(As a note about the glitched block at 1117, 57, 1628, this is where a block was supposed to move in the circuit. When this glitch first occurred, I moved the circuit back one block in attempt to fix it. This is why the glitched block does not line up with the pistons like the other three)

**Comment by martinjonsson01** [comment] 2018-02-07 22:40
Is this caused by colonies? If not then this might be a sponge bug, which we can't fix.

**Comment by GroxTerror** [comment] 2018-02-07 22:43
Not sure as I have not built redstone outside of colonies and I have had this happen only with this machine. Removing the glitched blocks would be nice though so the door would work again

**Comment by soronthar** [comment] 2018-02-09 04:57
This happens only in colonies, it is the same as #131. I have a test rig in my colony to show it.
I think the anti-griefing plugin left behind a technical block (maybe id:36?) when it prevented the block to be moved.

Pistons work correctly outside colony claims.

**Comment by Laserlance141** [comment] 2018-02-26 04:09
Also have this problem on Arenstad, there was also a drill involved, and I would also conclude it's probably block 36 involved, all the things that are happening are consistent with this

**Comment by GingerWalnut** [comment] 2018-03-03 00:59
Should be fixed

**Closed by GingerWalnut** 2018-03-03 00:59 UTC
Labels: Misc. Bug, Priority Low

**Comment by soronthar** [comment] 2018-03-03 04:03
Confirmed fixed.
