### ISSUE TITLE
Docking Tubes - Won't activate for players at spawn

### ISSUE THREAD

**Issue by swils24** [GingerWalnut/SQ5.0Public#39] opened 2017-12-29 15:09 UTC
Specifically, at coords:
-1306X 104Y 3380Z in space
Roughly 10:05-10:10 am EST, 29DEC

jorcool was unable to activate his docking tube sign.  It technically activated, and the sign changed, but no glass extended. When he tried to retract it, he got spammed with errors saying he didn't have permissions, though the sign changed back to 'retracted'.

When I activated the tube, it worked fine, extended/retracted.  When he tried to retract the tube I had extended, it broke--glass remained, but sign changed to retracted. Couldn't re-retract or extend it now, got an invalid tube error (as there was glass in the way)

**Comment by martinjonsson01** [comment] 2017-12-29 22:08
Duplicate of #12

**Closed by martinjonsson01** 2017-12-29 22:08 UTC
Labels: Duplicate
